Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -27,14 +27,15 @@ jobs:
 
       # Runs a single command using the runners shell
       - name: Check for empty files
-        run: | 
-            FILES=$(find . -empty | grep -v "./.git/")
-            if [ -n "$FILES" ]; then
-              echo "ERROR: empty files found:"
-              echo "$FILES"
-              exit 1
-            else
-              echo "No empty files found."
-              exit 0
-            fi
+        run: |
+          echo "Checking for empty files..."
+          FILES=$(find . -empty | grep -v "./.git/")
+          if [ -n "$FILES" ]; then
+            echo "ERROR: empty files found:"
+            echo "$FILES"
+            exit 1
+          else
+            echo "No empty files found."
+            exit 0
+          fi
 
